### GET all movies
GET http://localhost:8080/movies
Accept: application/json

###

### GET single movie by ID
# 👉 Reemplaza ID_REAL por un ID existente
GET http://localhost:8080/movies/ID_REAL
Accept: application/json

###

### POST new movie
POST http://localhost:8080/movies
Content-Type: application/json

{
  "title": "Inception",
  "genre": "Sci-Fi",
  "year": 2010,
  "rating": 9,
  "director": "Christopher Nolan",
  "duration": 148,
  "description": "A mind-bending thriller"
}

###

### POST movie with missing fields (should return 400)
POST http://localhost:8080/movies
Content-Type: application/json

{
  "title": "",
  "genre": "Action"
}

###

### PUT update movie
# 👉 Reemplaza ID_REAL por un ID existente
PUT http://localhost:8080/movies/ID_REAL
Content-Type: application/json

{
  "title": "Inception Updated",
  "genre": "Sci-Fi",
  "year": 2010,
  "rating": 10,
  "director": "Christopher Nolan",
  "duration": 148,
  "description": "Updated description"
}

###

### DELETE movie
# 👉 Reemplaza ID_REAL por un ID existente
DELETE http://localhost:8080/movies/ID_REAL
Accept: application/json


#############################################
###########  CATEGORIES TESTS  ##############
#############################################

### GET all categories
GET http://localhost:8080/categories
Accept: application/json

###

### GET category by ID
# 👉 Reemplaza ID_REAL con un ID existente
GET http://localhost:8080/categories/ID_REAL
Accept: application/json

###

### POST new category
POST http://localhost:8080/categories
Content-Type: application/json

{
  "name": "Adventure"
}

###

### POST category with missing fields (should return 400)
POST http://localhost:8080/categories
Content-Type: application/json

{
  "name": ""
}

###

### PUT update category
# 👉 Reemplaza ID_REAL por un ID existente
PUT http://localhost:8080/categories/ID_REAL
Content-Type: application/json

{
  "name": "Updated Category Name"
}

###

### DELETE category
# 👉 Reemplaza ID_REAL por un ID existente
DELETE http://localhost:8080/categories/ID_REAL
Accept: application/json
