### ==================== MOVIES ====================

### GET all movies
GET http://localhost:8080/movies
Accept: application/json

###

### GET single movie by ID
GET http://localhost:8080/movies/691d4778359113cceb723075
Accept: application/json

###

### POST new movie
POST http://localhost:8080/movies
Content-Type: application/json

{
  "title": "el origen",
  "genre": "Sci-Fi",
  "year": 2010,
  "rating": 9,
  "director": "Christopher Nolan",
  "duration": 148,
  "description": "A mind-bending thriller",
  "category": "691d620213c4763c84acbc4d"
}

###

### POST movie with missing fields (should return 400)
POST http://localhost:8080/movies
Content-Type: application/json

{
  "title": "",
  "genre": "Action"
}

###

### PUT update movie
PUT http://localhost:8080/movies/ID_HERE
Content-Type: application/json

{
  "title": "Inception Updated",
  "genre": "Sci-Fi",
  "year": 2010,
  "rating": 10,
  "director": "Christopher Nolan",
  "duration": 148,
  "description": "Updated description",
  "category": "691d620213c4763c84acbc4d"
}

###

### DELETE movie
DELETE http://localhost:8080/movies/ID_REAL
Accept: application/json


#############################################
###########  CATEGORIES TESTS  ##############
#############################################

### GET all categories
GET http://localhost:8080/categories
Accept: application/json

###

### GET category by ID
GET http://localhost:8080/categories/691d4eff81eae9504c6c3c47
Accept: application/json

###

### POST new category
POST http://localhost:8080/categories
Content-Type: application/json

{
  "name": "Sci-Fi"
}

###

### POST category with missing fields (should return 400)
POST http://localhost:8080/categories
Content-Type: application/json

{
  "name": ""
}

###

### PUT update category
PUT http://localhost:8080/categories/ID_REAL
Content-Type: application/json

{
  "name": "Updated Category Name"
}

###

### DELETE category
DELETE http://localhost:8080/categories/ID_REAL
Accept: application/json
